# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GewA6Vd_Fcdr1A0ou9HzoWdlwCIEGU5g
"""

import joblib
import os

# Save the scaler used during training
joblib.dump(scaler, 'scaler.pkl')
print("StandardScaler saved as 'scaler.pkl'.")

streamlit_app_code = """
import streamlit as st
import pandas as pd
import joblib
import os

# Define the path to the model and scaler files
MODEL_PATH = 'logistic_regression_model.pkl'
SCALER_PATH = 'scaler.pkl'

# Check if model and scaler files exist
if not os.path.exists(MODEL_PATH):
    st.error(f"Error: Model file '{MODEL_PATH}' not found. Please ensure it's in the same directory as the app.")
    st.stop()
if not os.path.exists(SCALER_PATH):
    st.error(f"Error: Scaler file '{SCALER_PATH}' not found. Please ensure it's in the same directory as the app.")
    st.stop()

# Load the trained model and scaler
try:
    model = joblib.load(MODEL_PATH)
    scaler = joblib.load(SCALER_PATH)
except Exception as e:
    st.error(f"Error loading model or scaler: {e}")
    st.stop()

st.set_page_config(page_title="Pathogenicity Prediction App", layout="centered")

st.title("🦠 Pathogenicity Prediction App")
st.markdown("---")
st.write("Enter the genetic features below to predict whether a bacterial strain is Pathogenic or Non-Pathogenic.")

st.sidebar.header("Input Features")

# Collect user input for features
gc_content = st.sidebar.number_input("GC Content Percentage", min_value=0.0, max_value=100.0, value=50.5, format="%.2f")
genome_size = st.sidebar.number_input("Genome Size (bp)", min_value=1000000, max_value=10000000, value=5000000)
virulence = st.sidebar.number_input("Virulence Factor Count", min_value=0, max_value=1000, value=300)
amr_gene = st.sidebar.number_input("AMR Gene Count", min_value=0, max_value=500, value=250)

# Create a DataFrame from the input
input_data = pd.DataFrame([[gc_content, genome_size, virulence, amr_gene]],
                          columns=['GC_content_percentage', 'Genome_size', 'Virulence', 'AMR_gene'])

st.subheader("Current Input Values:")
st.dataframe(input_data)

# Scale the input data
scaled_input = scaler.transform(input_data)

# Make prediction
if st.button("Predict Pathogenicity"):
    prediction = model.predict(scaled_input)
    prediction_proba = model.predict_proba(scaled_input)

    st.markdown("---")
    st.subheader("Prediction Result:")
    if prediction[0] == 1:
        st.success("✨ The model predicts this strain is **Pathogenic**.")
    else:
        st.info("🌿 The model predicts this strain is **Non-Pathogenic**.")

    st.markdown(f"**Confidence:**")
    st.write(f"- Non-Pathogenic: `{prediction_proba[0][0]*100:.2f}%`")
    st.write(f"- Pathogenic: `{prediction_proba[0][1]*100:.2f}%`")
    st.markdown("---")

"""

print("\n--- Streamlit App Code (Copy and save as app.py) ---\n")
print(streamlit_app_code)
print("\n--- End Streamlit App Code ---\n")

print("To run the Streamlit app:")
print("1. Copy the code between '--- Streamlit App Code ---' and '--- End Streamlit App Code ---' into a file named `app.py` on your local machine.")
print("2. Ensure `logistic_regression_model.pkl` and `scaler.pkl` are in the same directory as `app.py`.")
print("3. Open your terminal or command prompt, navigate to that directory, and run the command: `streamlit run app.py`")